### ISSUE TITLE
Apollo polishing using Illumina DNA + ONT DNA + PacBio RNA reads

### ISSUE THREAD

**Issue by 000generic** [CMU-SAFARI/Apollo#5]
I have the following reads: Illumina DNA + ONT DNA + PacBio RNA

I'm wondering if I could use all of these data stes to do hybrid polishing with Apollo.  

Specifically:

1) Does Apollo work well using ( Illumina DNA + ONT DNA ) reads for hybrid polishing?  

2) Does Apollo work well using long-read RNA-seq - for instance:  ( Illumina DNA + PacBio RNA) reads?

Thank you!
Eric

**Comment by canfirtina** [comment]
Hi Eric,

Here are the answers to your questions:

1- Apollo generally works well when using a hybrid set of reads than using only a single set of reads. However, we found that current settings of the default parameters are more favorable to using either PacBio or Illumina data sets. Apollo can still correct the errors in the assembly using the ONT data set but likely not as well as a hybrid of PacBio and Illumina.

2- Yes, this should work well.

Sorry for the late answer but hope this helps.

**Comment by 000generic** [comment]
Great!  This is very helpful :)
